
HASH = "hash"
PHONE_NUMBER = "phone_number"
OTP = "otp"
MESSAGE = "message"
PROFILE = "profile"
IS_VERIFIED = "is_verified"
OTP_MESSAGE = "hello"
OTP_URL = "https://2factor.in/API/V1/"
OTP_KEY = "ab399ef8-4704-11ec-a13b-0200cd936042/"
TEMPLATE_NAME = "Test1"
